In [6]:
print("hi")

hi

**Step 1 Data Exploration & loading**

In [7]:
#importing  dependencies 
import pandas as pd

print(pd.__version__)

2.3.3

In [8]:
df= pd.read_csv(C:\Users\kiera\OneDrive\Desktop\project walmarts\walmart_data\Walmart.csv,encoding_errors='ignore')
                
 df.shape

SyntaxError: invalid syntax (3461296274.py, line 1)

In [9]:
import os
print(os.listdir())

['Include', 'Lib', 'project.ipynb', 'pyvenv.cfg', 'requirements.txt', 'Scripts', 'share']

In [11]:
import os
os.getcwd()

'c:\\Users\\kiera\\OneDrive\\Desktop\\project walmarts\\my_env2'

In [14]:
import os

os.path.exists(r"../walmart_data/Walmart.csv")

True

In [13]:
df = pd.read_csv(r"../walmart_data/Walmart.csv")

df.shape

(10051, 11)

In [16]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [17]:
df.describe()

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  object
 2   City            10051 non-null  object
 3   category        10051 non-null  object
 4   unit_price      10020 non-null  object
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  object
 7   time            10051 non-null  object
 8   payment_method  10051 non-null  object
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 863.9+ KB

In [23]:
df.duplicated().sum()
df.drop_duplicates(implace = True)

TypeError: drop_duplicates() got an unexpected keyword argument 'implace'

In [25]:
df.drop_duplicates(inplace = True)

In [ ]:
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [26]:
df.dropna(inplace=True)

In [27]:
df.dtypes

invoice_id          int64
Branch             object
City               object
category           object
unit_price         object
quantity          float64
date               object
time               object
payment_method     object
rating            float64
profit_margin     float64
dtype: object

In [ ]:
df['unit_price'].astype(float)

In [36]:
df['unit_price']= df['unit_price'].str.replace('$','').astype(float)

AttributeError: Can only use .str accessor with string values!

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   Branch          9969 non-null   object
 2   City            9969 non-null   object
 3   category        9969 non-null   object
 4   unit_price      9969 non-null   float64
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   object
 7   time            9969 non-null   object
 8   payment_method  9969 non-null   object
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 934.6+ KB

In [38]:
df['total']= df['unit_price']* df['quantity']

In [39]:
#my sql connection

engine_mysql = create  engine()

SyntaxError: invalid syntax (1929001540.py, line 3)

In [41]:
from sqlalchemy import create_engine

engine_surya = create_engine("postgresql+psycopg2://postgres:1234@localhost:5432/walmarts_db")

try:
    with engine_surya.connect() as conn:
        print("Connection successful!")
except Exception as e:
    print("Connection failed:", e)

Connection successful!

In [44]:
df.to_sql(name='walmarts', con=engine_surya,if_exists='append',index=False)

C:\Users\kiera\AppData\Local\Temp\ipykernel_6224\2878842078.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df.to_sql(name='walmarts', con=engine_surya,if_exists='append',index=False)

AttributeError: 'Engine' object has no attribute 'cursor'

In [52]:
import pandas as pd
import sqlalchemy

print(pd.__version__)
print(sqlalchemy.__version__)

2.3.3
1.4.54

In [1]:
import sqlalchemy
print(sqlalchemy.__version__)

2.0.51

In [2]:
df.to_sql(name='walmarts', con=engine_surya,if_exists='append',index=False)

NameError: name 'df' is not defined

In [ ]:
new

In [3]:
import pandas as pd
from sqlalchemy import create_engine

In [5]:
df = pd.read_csv(r"../walmart_data/Walmart.csv")

In [6]:
from sqlalchemy import create_engine

engine_surya = create_engine("postgresql+psycopg2://postgres:1234@localhost:5432/walmarts_db")

try:
    with engine_surya.connect() as conn:
        print("Connection successful!")
except Exception as e:
    print("Connection failed:", e)

Connection successful!

In [10]:
df.to_sql(name='walmarts', con=engine_surya,if_exists='append',index=False)

51

In [8]:
df.columns

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin'],
      dtype='object')

In [9]:
df.columns= df.columns.str.lower()